apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: logging
  labels:
    k8s-app: fluent-bit
data:
  # Configuration files: server, input, filters and output
  # ======================================================
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Daemon        off
        Parsers_File  parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020
    @INCLUDE input-kubernetes.conf
    @INCLUDE filter-kubernetes.conf
    @INCLUDE output-kafka.conf
  input-kubernetes.conf: |
    [INPUT]
        Name tail
        Path /var/log/containers/*.log
        multiline.parser docker, cri
        Tag kube.*
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On
    [INPUT]
        Name tail
        Tag host.log.mail
        Parser sys_log_file
        Path /var/log/mail
        db /var/log/_mail_.db
    [INPUT]
        Name tail
        Tag host.log.secure
        Parser sys_log_file
        Path /var/log/secure
        db /var/log/_secure_.db
    [INPUT]
        Name tail
        Tag host.log.messages
        Parser sys_log_file
        Path /var/log/messages
        db /var/log/_messages_.db
    [INPUT]
        Name tail
        Tag host.log.cron
        Parser sys_log_file
        Path /var/log/cron
        db /var/log/_cron_.db
  filter-kubernetes.conf: |
    [FILTER]
        Name kubernetes
        Match kube.*
        Merge_Log On
        Keep_Log Off
        K8S-Logging.Parser On
        K8S-Logging.Exclude On
    [FILTER]
        Name modify
        Match host.log.mail
        Set app syslog
        Set file /var/log/mail
    [FILTER]
        Name modify
        Match host.log.secure
        Set app syslog
        Set file /var/log/secure
    [FILTER]
        Name modify
        Match host.log.messages
        Set app syslog
        Set file /var/log/messages
    [FILTER]
        Name modify
        Match host.log.cron
        Set app syslog
        Set file /var/log/cron
  output-kafka.conf: |
    [OUTPUT]
        Name        kafka
        Match       kube.*
        Brokers     ${FLUENT_KAFKA_HOST}:${FLUENT_KAFKA_PORT}
        Topics      kube  
    [OUTPUT]
        Name        kafka
        Match       host.log.*
        Brokers     ${FLUENT_KAFKA_HOST}:${FLUENT_KAFKA_PORT}
        Topics      host
  parsers.conf: |
    [PARSER]
        Name docker_no_time
        Format json
        Time_Keep Off
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
    [PARSER]
        Format regex
        Name sys_log_file
        Regex (?<message>(?<time>[^ ]*\s{1,2}[^ ]*\s[^ ]*)\s(?<host>[a-zA-Z0-9_\/\.\-]*)\s.*)$
        Time_Format %b %d %H:%M:%S
        Time_Keep Off
        Time_Key time
        Time_Offset +0300

