---
#users: 
#    prodadmin0: ['pass_PRODadmin0', 'group_PROD_admin0']
#    prodadmin1: ['pass_PRODadmin1', 'group_PROD_admin1']
credentials:
  users:
    psiadmin0:
      password: PRODadmin0
      groups: group_PROD_admin0
 
    psiadmin1:
      password: PRODadmin1
      groups: group_PROD_admin1