apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-nfs
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  nfs:
    path: /var/nfs-disk/static-pv
    server: 192.168.1.170
  persistentVolumeReclaimPolicy: Retain
