# запуск тестовой задачи которая выводит название ОС целевой машины

- name: Print test message 
  ansible.builtin.debug:
    msg: test message in task install_alertmanager.yml

# создание пользователя 
- name: Create User Alertmanager
  user:
    name: alertmanager
    create_home: no
    shell: /bin/false

# создание целевых каталогов
- name: Create Directories For Alertmanager
  file:
    path: "{{ item }}"
    state: directory
    owner: alertmanager
    group: alertmanager
  loop:
    - '/tmp/alertmanager'
    - '/etc/alertmanager'
    - '/var/lib/prometheus/alertmanager'

# загрузка  https://github.com/prometheus/alertmanager/releases/download/v0.24.0/alertmanager-0.24.0.linux-amd64.tar.gz
- name: Download And Unzipped Alertmanager
  unarchive:
    src: https://github.com/prometheus/alertmanager/releases/download/v{{ alertmanager_version }}/alertmanager-{{ alertmanager_version }}.linux-amd64.tar.gz
    dest: /tmp/alertmanager
    creates: /tmp/alertmanager/alertmanager-{{ alertmanager_version }}.linux-amd64
    remote_src: yes

#  копирование бинарных файлов (prometheus, promtool) в целевые каталоги 
#  mode: preserve  означает, что файлу будут предоставлены те же разрешения, что и исходному файлу.
- name: Copy Bin Files From Unzipped to Alertmanager
  copy: 
    src: /tmp/alertmanager/alertmanager-{{ alertmanager_version }}.linux-amd64/{{ item }}
    dest: /usr/local/bin/
    remote_src: yes
    mode: preserve
    owner: alertmanager
    group: alertmanager
  loop: [ 'alertmanager', 'amtool' ]

#  копирование конфигруационных файлов и каталогов  (prometheus.yml, console_libraries, consoles) в целевые каталоги 
- name: Copy Conf File From Unzipped to Alertmanager
  copy: 
    src: /tmp/alertmanager/alertmanager-{{ alertmanager_version }}.linux-amd64/alertmanager.yml
    dest: /etc/alertmanager/
    remote_src: yes
    mode: preserve
    owner: alertmanager
    group: alertmanager

# создание systemdunit для сервиса alertmanager
# ./ROLES/ansible/roles/prometheus/templates/alertmanager.service 
- name: Create File for Alertmanager Systemd
  template:
    src=templates/alertmanager.service
    dest=/etc/systemd/system/
  notify:
    - systemd reload

- name: Systemctl Alertmanager Start
  systemd:
    name: alertmanager
    state: started
    enabled: yes