
---
# запуск тестовой задачи которая выводит название ОС целевой машины
- name: Print test message 
  ansible.builtin.debug:
    msg: test message in task prepare.yml

# Описание основной роли 
# 9090/tcp - http://Server-IP:9090/graph
# 9093/tcp - http://IP-Address:9100/#/alerts
# 9094/tcp - Alertmanager
# 9100/tcp - http://IP-Address:9100/metrics
# 9094/udp - Alertmanager
# 22/tcp   - ssh

- name: Security Settings For RedHat
  block:
    - name: firewall enabled
      ansible.builtin.systemd:
        name: firewalld
        state: started
        enabled: yes
      
    - name: Allow Ports
      firewalld:
        port: "{{ item }}"
        permanent: true
        state: enabled
      loop: [ '9090/tcp', '9093/tcp', '9094/tcp', '9100/tcp', '9094/udp', '22/tcp' ]
      notify:
        - resatrt firewalld

    - name: Disable SELinux
      selinux:
        state: disabled

    - name: Stop SELinux
      shell: setenforce 0
      ignore_errors: true
  when:
    ansible_os_family == "RedHat"

# не тестировалась
- name: Security Settings For Debian
  block:
    - name: Allow TCP Ports
      iptables:
        chain: INPUT
        rule_num: '1'
        action: insert
        protocol: tcp
        jump: ACCEPT
        destination_port: "{{ item }}"
      loop: [ '9090', '9093', '9094', '9100', '22' ]

    - name: Allow UDP Ports
      iptables:
        chain: INPUT
        rule_num: '1'
        action: insert
        protocol: udp
        jump: ACCEPT
        destination_port: '9094'
  when:
    ansible_os_family == "Debian"

  handlers:
  - name: restart firewalld
    ansible.builtin.service:
      name: firewalld
      state: restarted