apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-app1-pod1
  namespace: app1
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: service-app1-pod1
            port:
              number: 80