---
# handlers file for v1
- name: restart firewalld
  #command: firewall-cmd --reload   
  ansible.builtin.service:
    name: firewalld
    state: restarted

- name: systemd reload
  systemd:
    daemon_reload: yes