# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\SOURCE\Pycharm\venv\computeArea\computeArea.ui',
# licensing of 'E:\SOURCE\Pycharm\venv\computeArea\computeArea.ui' applies.
#
# Created: Thu Sep 13 16:39:16 2018
#      by: pyside2-uic  running on PySide2 5.11.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_computeArea(object):
    def setupUi(self, computeArea):
        computeArea.setObjectName("computeArea")
        computeArea.resize(356, 528)
        computeArea.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget = QtWidgets.QWidget(computeArea)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.shape_cbb = QtWidgets.QComboBox(self.groupBox)
        self.shape_cbb.setMinimumSize(QtCore.QSize(0, 40))
        self.shape_cbb.setObjectName("shape_cbb")
        self.shape_cbb.addItem("")
        self.shape_cbb.addItem("")
        self.verticalLayout.addWidget(self.shape_cbb)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.sq_gb = QtWidgets.QGroupBox(self.centralwidget)
        self.sq_gb.setObjectName("sq_gb")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.sq_gb)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.sq_gb)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.sq_heigth_spx = QtWidgets.QSpinBox(self.sq_gb)
        self.sq_heigth_spx.setMinimumSize(QtCore.QSize(150, 40))
        self.sq_heigth_spx.setMinimum(10)
        self.sq_heigth_spx.setMaximum(9999999)
        self.sq_heigth_spx.setObjectName("sq_heigth_spx")
        self.horizontalLayout.addWidget(self.sq_heigth_spx)
        self.horizontalLayout.setStretch(0, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.sq_gb)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.sq_weight_spx = QtWidgets.QSpinBox(self.sq_gb)
        self.sq_weight_spx.setMinimumSize(QtCore.QSize(150, 40))
        self.sq_weight_spx.setMinimum(10)
        self.sq_weight_spx.setMaximum(9999999)
        self.sq_weight_spx.setObjectName("sq_weight_spx")
        self.horizontalLayout_2.addWidget(self.sq_weight_spx)
        self.horizontalLayout_2.setStretch(0, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addWidget(self.sq_gb)
        self.sr_gb = QtWidgets.QGroupBox(self.centralwidget)
        self.sr_gb.setObjectName("sr_gb")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.sr_gb)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.sr_gb)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.cr_radius_spx = QtWidgets.QSpinBox(self.sr_gb)
        self.cr_radius_spx.setMinimumSize(QtCore.QSize(150, 40))
        self.cr_radius_spx.setMinimum(10)
        self.cr_radius_spx.setMaximum(9999999)
        self.cr_radius_spx.setObjectName("cr_radius_spx")
        self.horizontalLayout_3.addWidget(self.cr_radius_spx)
        self.horizontalLayout_3.setStretch(0, 1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addWidget(self.sr_gb)
        self.compute_btn = QtWidgets.QPushButton(self.centralwidget)
        self.compute_btn.setMinimumSize(QtCore.QSize(0, 40))
        self.compute_btn.setObjectName("compute_btn")
        self.verticalLayout_2.addWidget(self.compute_btn)
        self.result_lb = QtWidgets.QLabel(self.centralwidget)
        self.result_lb.setMinimumSize(QtCore.QSize(0, 40))
        self.result_lb.setAlignment(QtCore.Qt.AlignCenter)
        self.result_lb.setObjectName("result_lb")
        self.verticalLayout_2.addWidget(self.result_lb)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        computeArea.setCentralWidget(self.centralwidget)

        self.retranslateUi(computeArea)
        QtCore.QMetaObject.connectSlotsByName(computeArea)

    def retranslateUi(self, computeArea):
        computeArea.setWindowTitle(QtWidgets.QApplication.translate("computeArea", "Compute Area ", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("computeArea", "Select formula", None, -1))
        self.shape_cbb.setItemText(0, QtWidgets.QApplication.translate("computeArea", "Square", None, -1))
        self.shape_cbb.setItemText(1, QtWidgets.QApplication.translate("computeArea", "Circle", None, -1))
        self.sq_gb.setTitle(QtWidgets.QApplication.translate("computeArea", "Square", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("computeArea", "Height", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("computeArea", "Weight", None, -1))
        self.sr_gb.setTitle(QtWidgets.QApplication.translate("computeArea", "Circle", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("computeArea", "Radius", None, -1))
        self.compute_btn.setText(QtWidgets.QApplication.translate("computeArea", "COMPUTE", None, -1))
        self.result_lb.setText(QtWidgets.QApplication.translate("computeArea", "RESULT", None, -1))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    computeArea = QtWidgets.QMainWindow()
    ui = Ui_computeArea()
    ui.setupUi(computeArea)
    computeArea.show()
    sys.exit(app.exec_())

