apiVersion: apps/v1
kind: Deployment
metadata:
  name: dnstools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dnstools
  template:
    metadata:
      labels:
        app: dnstools
    spec:
      hostname: dns
      subdomain: tools
      hostAliases:
        - ip: 8.8.8.8
          hostnames:
            - dns.google.local
            - dns8.google.local
        - ip: 8.8.4.4
          hostnames:
            - dns4.google.local
      containers:
        - name: dnstools
          image: infoblox/dnstools:latest
          command:
            - sleep
            - "36000"
          imagePullPolicy: IfNotPresent
      restartPolicy: Always