- hosts: nodeexporter
  vars:
    # указываем версию раскатки 
    - node_exporter_role: "v1"
  roles:
    # относитьльный от ../roles/<путь до роли> 
    # выпрыгиваем из каталога playbooks monitoring 
    - ../roles/nodeexporter/{{ node_exporter_role }}   

     
   