---
apiVersion: v1
kind: Service
metadata:
  name: node-port-kubernetes-dashboard
  namespace: kubernetes-dashboard
  labels:
    k8s-app: kubernetes-dashboard
spec:
  selector:
    k8s-app: kubernetes-dashboard
  type: NodePort	
  ports:
  - port: 443
    protocol: TCP
    targetPort: 8443
    nodePort: 30800
  sessionAffinity: None

