apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: access-openresty
  namespace: volumes-sample
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: openresty-srv
            port:
              number: 80
