apiVersion: v1
kind: Service
metadata:
  name: test-service-nodeport-nginx
spec:
  selector:
    type: test-front
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 30090 

