apiVersion: v1
kind: Namespace
metadata:
  name: test-volumes-sample
  labels:
    app: test-volumes-sample

---
apiVersion: v1
kind: Service
metadata:
  name: test-openresty-srv
  namespace: test-volumes-sample
  labels:
    app: test-openresty-srv
spec:
  type: ClusterIP
  selector:
    app: test-openresty
  ports:
    - protocol: TCP
      port: 80
      targetPort: http

