---
- name: Upgrade kubernetes cluster
  hosts: k8s_cluster
  # serial: "1" - проводить измения по одному серверу а не на всех сразу (rolling update)
  serial: "1"
  vars:
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - upgrade-cluster
