apiVersion: v1
kind: Namespace
metadata:
  name: volumes-sample
  labels:
    app: volumes-sample

---
apiVersion: v1
kind: Service
metadata:
  name: openresty-srv
  namespace: volumes-sample
  labels:
    app: openresty-srv
spec:
  type: ClusterIP
  selector:
    app: openresty
  ports:
    - protocol: TCP
      port: 80
      targetPort: http

