apiVersion: storage.k8s.io/v1
# https://kubernetes.io/docs/concepts/storage/storage-classes/
kind: StorageClass
metadata:
  name: managed-nfs-storage
provisioner: kube.local/nfs     # or choose another name, must match deployment env PROVISIONER_NAME
parameters:
  archiveOnDelete: "false"
