// как включить скрип в pipeline

def code
pipeline {
    agent any
    stages {
        stage('stage 1'){
            steps {
                sh 'echo "stage 1"'
                script {
                    code = load './scripts/hello.groovy'
                    code.example1()
                }
            }
        }
        stage('stage 2'){
            steps {
                sh 'echo "stage 2"'
                script {
                    code.example1()
                }
            }
        }
    }
}

// Repository URL
// https://github.com/j1nn33/study.git
// Script Path
// Jenkins/example_pipeline/Jenkinsfile