---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "openresty-art.fullname" . }}-html
data:
{{- range $file, $value :=  .Values.html }}
  {{ $file }}.html: |
{{ $value | indent 4 }}
{{- end }}