---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "openresty-art.fullname" . }}-html
data:
{{- range $path, $_ :=  .Files.Glob  "html/*" }}
  {{ base $path }}: |
{{ $.Files.Get $path | indent 4 }}
{{- end }}