kind: Service
apiVersion: v1
metadata:
  name: {{ include "openresty-art.fullname" . }}-srv
  labels:
    {{- include "openresty-art.labels" . | nindent 4 }}
  {{- if .Values.application.reloader }}
  annotations:
    reloader.stakater.com/auto: "true"
    configmap.reloader.stakater.com/reload: {{ include "openresty-art.fullname" . }}-conf,{{ include "openresty-art.fullname" . }}-html
  {{- end }}
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    k8s-app: openresty
