fullnameOverride: "art"

application:
  reloader: true
  podAnnotations:
#  если раскоментить то поедут в deployment в таком виде как есть  
#    prometheus.io/scrape: "true"
#    prometheus.io/path: "/metrics"
#    prometheus.io/port: "80"
#  если используется секрет к docker registry
#  imagePullSecrets: []   
#  или
#  imagePullSecrets:
#    - name: MypullSecretName  

# берем значения из  ./study/K8S/helm/teach_example/base-application/deployment.yaml 
  probes:
    readinessProbe:
      httpGet:
        path: /index.html
        port: http
      initialDelaySeconds: 5
      periodSeconds: 15
    livenessProbe:
      httpGet:
        path: /index.html
        port: http
      initialDelaySeconds: 5
      periodSeconds: 15
      timeoutSeconds: 5
  resources:
    limits:
      cpu: "0.2"
      memory: "400Mi"
    requests:
      cpu: "0.1"
      memory: "200Mi"