---
# Примениен настройки на файл krb5.conf по тегу krb5-policy
# вывод тестового сообщения
- name: message
  ansible.builtin.debug:
    msg: updating_krb5.conf

# Обновляем krb5.conf 
- name: Template a file to /etc/krb5.conf
  ansible.builtin.template:
    src: krb5.j2
    dest: /etc/krb5.conf
    owner: root
    group: root
    mode: '0644'
    backup: true
