---
# tasks file for v1
# запуск тестовой задачи которая выводит название ОС целевой машины
- name: Debug
  debug: msg={{ ansible_os_family }}

# установка состоит из 2 этапов (подготовка, установка )
# будет разложена по 2 файлам (prepare.yml install_nodeexporter.yml) не считая main.yml

- name: Prepare For Install Node_Exporter
  include_tasks: tasks/prepare.yml

- name: Install Node_Exporter
  include_tasks: tasks/install_node_exporter.yml