---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap_1
data:
  # В данном случае, всё что после символа | - это многострочное значение ключа default.conf
  default.conf: |
    server {
        listen       80 default_server;
        server_name  _;

        default_type text/plain;

        location / {
            return 200 '$hostname\n';
        }
    location /files {
        alias /data;
        autoindex on;
        client_body_temp_path /tmp;
        dav_methods PUT DELETE MKCOL COPY MOVE;
        create_full_put_path on;
        dav_access user:rw group:rw all:r;
      }
    }
  # Многострочное значение оканчивается там, где отступ будет меньше чем в начале этого значения,
  # т.е. на том же уровне, что и у ключа, в нашем случае default.conf
...