---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: openresty
  name: openresty
  namespace: q-test
spec:
  ports:
  - name: http
    port: 3080
    protocol: TCP
    targetPort: 80
  selector:
    app: openresty
  type: NodePort

