apiVersion: v1
kind: Pod
metadata:
  name: downward-api-demo-dynamic
  labels:
    app.kubernetes.io/name: downward-demo-dynamic
    status: pending
spec:
  containers:
    - name: main
      image: busybox:1.37
      command: ["/bin/sh", "-c"]
      args:
        - |
          while true; do
            echo "-------";
            echo "Reading labels at $(date):";
            cat /etc/podinfo/labels;
            sleep 10;
          done
      resources:
        limits:
          cpu: "200m"
          memory: "64Mi"
        requests:
          cpu: "200m"
          memory: "32Mi"
      volumeMounts:
        - name: podinfo
          mountPath: /etc/podinfo   
  volumes:
    - name: podinfo
      downwardAPI:
        items:
          - path: "labels"
            fieldRef:
              fieldPath: metadata.labels
  restartPolicy: Never

