apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fluentd-forward-pvc
  namespace: logging
spec:
  storageClassName: "managed-nfs-storage"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
