---
# handlers file for v1

- name: restart firewalld
  #command: firewall-cmd --reload   
  ansible.builtin.service:
    name: firewalld
    state: restarted

- name: grafana systemd
  systemd:
    name: grafana-server
    enabled: yes
    state: started