---
- name: ROLE_1
  hosts: all
  gather_facts: false
  become: true
  vars_files: 
    - secret.yml
  roles:
    - role_1  
  tasks:
    - name: task_in_role_1
      ansible.builtin.debug:
      msg: test message in task_in_role_1.yml