apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service }}
spec:
  ports:
  - port: {{ .Values.port | default 80 }}
    targetPort: {{ .Values.port | default 80 }}
  selector:
    app: {{ .Chart.Name }} 
  type: ClusterIP
