---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: etcd-client
  namespace: monitoring
data:
  apiserver-etcd-client.crt: >-
    LS0tLS1CRUdJTiBDRVJUSU
  apiserver-etcd-client.key: >-
    LS0tLS1CRUdJTiBSU0EgUF
